package me.nvliu.management.web.dao;

import me.nvliu.management.web.entity.User;
import me.nvliu.management.web.entity.UserRole;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public int insertSelective(User record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    public int updateByPrimaryKeySelective(User record);

    /**
     *  通过用户名获取用户信息
     * @param username 用户名
     * @return User 对象
     */
    public User findByUserName(String username);

    public List<User> getUserList(User user);

    public int removeUserRole(User user);

    public int addUserRole(UserRole userRole);

}